### ISSUE TITLE
Set variable's value

### ISSUE THREAD

**Issue by albertattard** [sociable-weaver/web-vue3#10]
The user can customise the contents through variables.  For example, consider the following code fragment

```shell
$ echo "Albert Attard"
```

The above example is not customisable.  Instead of using hardcoded values, like the example above, we can use variables.  The user will provide the name to be printed as a variable input, as shown next.

![Variable input](https://user-images.githubusercontent.com/3372288/145008573-ef0a93db-570a-4181-b083-645c49f2a922.png)

Once the user sets the variable, say with the value `Hello world`, the entries coming after the variable declaration should be updated, as shown below.

```shell
$ echo "Hello world"
```

The user sees the variable's value instead of the hardcoded value.

We need to consider the following cases
- *Default values*: should we have default values? And if so, should we display/use the default values until these are changed?
- *Sensitive values*: variables can be sensitive in which case these should not be printed.  Instead we can display `******`.  When the command is then executed, using the run action that will be added, the real (sensitive) value is used.

## Tasks

- [ ] Display/use the default value when one is provided
- [ ] Capture the variable's value
- [ ] Show the variable's value if the variable is marked not sensitive, otherwise mask the value
- [ ] Update the entries and show the variable's value instead of the variable
