### ISSUE TITLE
Run runnable entries

### ISSUE THREAD

**Issue by albertattard** [sociable-weaver/web-vue3#12]
Some of the entries are runnable, which means that the user can run them on their computer by, for example, pressing a _Run_ button.  When the user presses the _Run_ button, the application (running in the background) should run this _runnable entry_ on the set workspace folder and working directory.

Some _runnable entries_ may require variables (see #10).  In this case, the variable value needs to be used when running the _runnable entry_.  If the variables values are missing, then a warning should be shown to the user.

When the _runnable entry_ is executed by the application, the _runnable entry_'s output should be displayed to the user, ideally in real time.  By real time, it is mean that the output should be shown to the user as this becomes available and not waiting for the _runnable entry_ to terminate.  Some _runnable entries_ take longer than others to run and the user should not be left guessing what's happening.

_Runnable entries_ should not run forever and should have a sensible timeout (this is more of a backend issue than frontend).

_Runnable entries_ may succeed or fail. Indicate whether the _runnable entry_ ran as expected or not.  Sometimes the _runnable entry_ is expected to fail, in which case this can be considered as a success.  Other times, the errors are ignore, in which case the _runnable entry_ always succeeds.

## Tasks

- [ ] Provide means by which the user can run a given _runnable entry_, such as a button.
- [ ] Prevent the user from re-running the same _runnable entry_ until the command has finished, by for example disabling the button
  This can be tricky as the user can, trigger a long running _runnable entry_, reload the page, and re-trigger the _runnable entry_ again.  This is acceptable behaviour and no need to get too sophisticated.
- [ ] Show a warning if the _runnable entry_ is missing variable values
- [ ] Display the produced output in real-time
  By real time, it is meant, do not wait for the _runnable entry_ to finish to display the output.  Instead display this as it becomes available.  WebSockets can be used to deal with this problem.
- [ ] Indicate whether the _runnable entry_ has produced the expected outcome.
  Note that a _runnable entry_ may be expected to fail, in which case a failure is the expected outcome.  Furthermore, the outcome of the _runnable entry_ may be ignored.  This is ideally in cases where we need to delete something to have a clean slate and the _runnable entry_ will fail if that thing to be deleted is not there.
