### ISSUE TITLE
Open a chapter

### ISSUE THREAD

**Issue by albertattard** [sociable-weaver/web-vue3#7]
Once a book is opened, the user should be able to select and open one of the chapters in the book.

## Tasks

- [x] Allow the user to click on one of the chapters
- [x] Show the chapter contents
  A chapter comprise from different entries, such as _chapter_, _section_ and _subsection_, _command_, _markdown_, and the like.  No need to render these in any special way, as that' covered by #9 
- [x] Allow the user to switch between chapters
- [x] (Optional) Show the same content when the user reloads/refresh the page
  Note that we have not yet agreed on a strategy of how we can do this at a project level.
