### ISSUE TITLE
Render the chapter content

### ISSUE THREAD

**Issue by albertattard** [sociable-weaver/web-vue3#9]
The backend will return a JSON array of entries, similar to the following example:

```json
[
  {
    "type": "command",
    "parameters": [
      "run",
      "me"
    ],
    "name": "Test Command",
    "workingDirectory": "test-command",
    "environmentVariables": [
      "TEST_VAR_1",
      "TEST_VAR_2"
    ],
    "ignoreErrors": true,
    "pushChanges": true,
    "dryRun": true,
    "visible": true,
    "sensitive": true,
    "expectedExitValue": 1,
    "commandTimeout": 300.000000000
  }
]
```

**This is not the final version and it will change**.

There are many types, such as `chapter` or `markdown`, and each needs to be rendered differently.  The rendering of each entry does not need to be perfect, as this can be fine-tuned at a later stage.  For example, the `command` entry can be simply rendered within the HTML `pre` tag.

Some entries may require interaction, such as run for the `command` entry or input for the `variable` entry.  The interaction is out of the scope of this story and will be covered by other stories.

## Tasks

- [x] Render the `chapter` type:

  ```json
  {
    "type": "chapter",
    "id": "37a31d06-f5de-4e48-b47f-82e44f77c857",
    "parameters": [
      "Hello World"
    ]
  }
  ```

- [x] Render the `command` type:

  ```json
  {
    "type": "command",
    "id": "4fc50610-27b6-4ed1-92ba-69ab82c98199",
    "name": "Compile program",
    "workingDirectory": "hello-world",
    "parameters": [
      "javac",
      "HelloWorld.java"
    ]
  }
  ```

  The user will be able to interact with this by running the command.  This is not part of this story and will be handled by another story.

- [x] Render the `create` type:

  ```json
  {
    "type": "create",
    "id": "b9d4b6c5-c802-4f70-83bd-93e01d848262",
    "name": "Create Hello World",
    "workingDirectory": "hello-world",
    "parameters": [
      "HelloWorld",
      "#!/usr/bin/java --source 17",
      "",
      "public class HelloWorld {",
      "    public static void main(final String[] args) {",
      "        System.out.println(\"Hello World!!\");",
      "    }",
      "}",
      ""
    ]
  }
  ```

- [x] Render the `docker-tag-and-push` type:

  ```json
  {
    "type": "docker-tag-and-push",
    "id": "021ae3d4-7413-4992-92fb-ff147ca3c875",
    "name": "Tag and push Docker image",
    "workingDirectory": "hello-world",
    "parameters": [
      "hello-world:v8.0.4",
      "${DOCKER_USERNAME}/hello-world:v8.0.4"
    ],
    "environmentVariables": [
      "DOCKER_USERNAME"
    ]
  }
  ```

- [x] Render the `download` type:

  ```json
  {
    "type": "download",
    "id": "3b07c50d-1f63-4f81-985e-a9d92f7fb888",
    "name": "Download demo program",
    "workingDirectory": "hello-world",
    "parameters": [
      "https://github.com/albertattard/programming--hello-world-jar-demo/releases/download/v1.0.0/hello-world-jar-demo.jar",
      "hello-world-jar-demo.jar"
    ]
  }
  ```

- [x] Render the `git-apply-patch` type:

  ```json
  {
    "type": "git-apply-patch",
    "id": "ecfce538-d727-4b33-9d7d-3392263f147e",
    "name": "Use method parameter",
    "workingDirectory": "hello-world",
    "parameters": [
      "diff --git a/HelloWorld.java b/HelloWorld.java",
      "index da1e310..c6e7c66 100755",
      "--- a/HelloWorld.java",
      "+++ b/HelloWorld.java",
      "@@ -4,6 +4,6 @@ public class HelloWorld {",
      "     }",
      " ",
      "     private static void printMessage(final String message) {",
      "-        System.out.printf(\"[%tF %<tT] Hello World!!%n\", System.currentTimeMillis());",
      "+        System.out.printf(\"[%tF %<tT] %s%n\", System.currentTimeMillis(), message);",
      "     }",
      " }",
      ""
    ]
  }
  ```

- [x] Render the `git-commit-changes` type:

  ```json
  {
    "type": "git-commit-changes",
    "id": "b27bcd44-c0e8-44ca-bfaf-8a12b8c84fc3",
    "name": "Commit changes",
    "workingDirectory": "hello-world",
    "parameters": [
      "Generalize messages",
      "v3.0.9"
    ]
  }
  ```

- [x] Render the `git-tag-current-commit` type:

  ```json
  {
    "type": "git-tag-current-commit",
    "id": "7f3217d8-8db3-40a4-a4a8-974df073765f",
    "name": "Create starting point",
    "workingDirectory": "hello-world",
    "parameters": [
      "v4.0.0",
      "Start of Distribute Application"
    ]
  }
  ```

- [x] Render the `markdown` type:

  ```json
  {
    "type": "markdown",
    "id": "47169f83-0024-4df7-837d-e75bc0046c75",
    "parameters": [
      "‘Hello World’ is the first program that many programmers write, and this text will not break the tradition. We will",
      "stretch this beyond programming and use it as excuse to introduce dependency management, testing, and automation,"
    ]
  }
  ```

  The example was truncated for brevity.

- [x] Render the `replace` type:

  ```json
  {
    "type": "replace",
    "id": "ff00acef-231c-4e0a-b5ca-61a99f235cbf",
    "name": "Add the Gradle plugins",
    "workingDirectory": "hello-world",
    "parameters": [
      "build.gradle",
      "plugins {",
      "    id \"application\"",
      "}",
      ""
    ]
  }
  ```

- [x] Render the `section` type:

  ```json
  {
    "type": "section",
    "id": "d7c92ce7-98c8-43c8-a414-606cc6e85850",
    "parameters": [
      "Testing"
    ]
  }
  ```

- [x] Render the `subsection` type:

  ```json
  {
    "type": "subsection",
    "id": "97533798-c0a5-4eb0-9579-c690b56561c8",
    "parameters": [
      "JUnit"
    ]
  }
  ```

- [x] Render the `variable` type:

  ```json
  {
    "type": "variable",
    "id": "08298402-b313-4bae-a368-bb9dbe83a4e1",
    "name": "NAME",
    "sensitive": false
  }
  ```

  The user will be able to provide values to variable to customise the experience. For example, the next shown command might require a name to be printed. The user can provide the name and then when they execute the command, the given name is printed.  As part of this story we only need to render the inputs which can be either text or password (when `sensitive` is `true`).
